### ISSUE TITLE
index.html hardcodes URLs from gcping-1369

### ISSUE THREAD

**Issue by DazWilkin** [ImJasonH/gcping#10]
index.html references endpoints from (I assume) gcping-1369 rather than the user's project:

```
const _URLS = {
  'gce-us-central1':          'http://104.197.165.8/ping',
  'gce-us-east1':             'http://104.196.161.21/ping',
  'gce-us-east4':             'http://35.186.168.152/ping',
  'gce-us-west1':             'http://104.199.116.74/ping',
  'gce-europe-west1':         'http://104.199.82.109/ping',
  'gce-europe-west2':         'http://35.189.67.146/ping',
  'gce-asia-east1':           'http://104.155.201.52/ping',
  'gce-asia-northeast1':      'http://104.198.86.148/ping',
  'gce-asia-southeast1':      'http://35.185.179.198/ping',
  'gce-australia-southeast1': 'http://35.189.6.113/ping',
  'gce-global':               'http://35.186.221.153/ping',
}
```

**Comment by imjasonh** [comment]
Yeah, I have plans to make this easily hosted on other projects.

Namely, reimplement setup.sh as a GAE cron task that executes hourly to make sure everything's working, pick up new regions/addresses, and fill in the right addresses in the frontend.

Stay tuned! :)

**Comment by DazWilkin** [comment]
I can get you nearer ;-)

Remove the static definition of _URLS from your HTML and replace with something identifiable

```
ENDPOINTS={\
$(\
  # enumerate the project's (regions') IPs and format as a list of name,address pairs
  gcloud compute addresses list \
  --project=${PROJECT} \
  --format="csv[no-heading](name,address)" \
  |   # map $name,$address pairs to JSON elements "gce-$name": "$address" and a comma
  awk -F"," '{printf "\"gce-%s\":\"%s\",",$1,$2}' \
  | # remove the trailing comma
  sed 's/,$//g'
)\
}
```
Then sed the HTML identifiable value with ${ENDPOINTS}

**Comment by imjasonh** [comment]
The long-term goal is to excise all Bash from this repo and make it a Real Thing :tm:

Step 1 is to statically describe the stack using Deployment Manager (#5, currently underway), that would go a long way. Then all that's left is templatizing the static file and running it periodically.

PRs welcome! :)
