### ISSUE TITLE
Measure latency between regions

### ISSUE THREAD

**Issue by imjasonh** [ImJasonH/gcping#2]
Periodically ping between regions and record latency somewhere (BigQuery too?).

**Comment by nodesocket** [comment]
👍  would be great for setting up cross region clusters. For example latency from Iowa to South Carolina vs Iowa to North Carolina?

**Comment by zbjornson** [comment]
There's a separate project that does this: http://www.gcloudping.com/

**Comment by imjasonh** [comment]
https://cloud.google.com/vpc/docs/vpc
