### ISSUE TITLE
New asia regions

### ISSUE THREAD

**Issue by jmcbee** [ImJasonH/gcping#21]
Hello,
Thanks for the wonderful project! There are now 9 regions in asia. I hope you get a chance to add them. Cheers!

![screen shot 2018-06-03 at 1 54 55 pm](https://user-images.githubusercontent.com/8855087/40883685-bfe838ac-6735-11e8-9d20-2663242b4a07.jpg)

**Comment by imjasonh** [comment]
These regions are already included.
