### ISSUE TITLE
Public usage permission?

### ISSUE THREAD

**Issue by vkedwardli** [ImJasonH/gcping#27]
https://github.com/ImJasonH/gcping/blob/master/config.js

Is it allowed for other project to use the URLs for latency checking?

https://github.com/inada-s/gdxsv
We have a gaming server which dynamically allocate Google Cloud Compute Engine for players, and I'm seeking the possibility to know the latency between players and server first, before allocating the server successfully.

Thanks!

**Comment by imjasonh** [comment]
I'd prefer you didn't, since it means I might break you if I change how gcping works.

If you want to fork and run gcping yourself to get this information you're more than welcome to, which will guarantee it doesn't change unexpectedly.

**Comment by vkedwardli** [comment]
Sure thing thanks a lot!
