### ISSUE TITLE
Please add missing regions

### ISSUE THREAD

**Issue by vprelovac** [ImJasonH/gcping#32]
us-west2
us-west3
us-west4

seem to be missing from the service.

**Comment by imjasonh** [comment]
These locations are not currently supported by Cloud Run: https://cloud.google.com/run/docs/locations

**Comment by vprelovac** [comment]
Perhaps, you can use a different technology to ping those.

Saying this mainly because service is called GCP ping and not Cloud Run Ping, and those are valid GCP service locations.

**Comment by vprelovac** [comment]
I found the service as had a use case of deciding the proper location for our US west deployment and then noticed that is pinging only one out of four location, before actually digging into how the service was made (but was advertised as GCP ping which is why I clicked the link).

I'd argue that US west is very popular and missing 3/4 locations here decreases the value of service substantially.

**Comment by imjasonh** [comment]
Thanks for that feedback. Prior to [migrating to Cloud Run](https://github.com/ImJasonH/gcping/issues/29), those regions were available, backed by f1-micro GCE VMs that ran 24/7. I migrated to Cloud Run to lower the cost of running this free service.

When/if Cloud Run supports those regions, I'll happily add them. If there's a specific wording or warning you'd like to add to the homepage, feel free to open a PR on [index.html](https://github.com/ImJasonH/gcping/blob/main/cmd/ping/kodata/index.html).

**Comment by vprelovac** [comment]
Perhaps check what are they pinging

https://cloudpingtest.com/gcp

**Comment by imjasonh** [comment]
> Perhaps check what are they pinging

Chrome DevTools says they're hitting http://us-west4.gce.cloudharmony.net/, which seems to be a full VM running CentOS. Those VMs seem to be _not_ owned by cloudpingtest.com, but instead by cloudharmony.com, which they also use to power http://cloudharmony.com/speedtest-for-google.

Cloud Harmony [seems to be funded by Gartner](https://cloudharmony.com/about), and provides [paid services](https://cloudharmony.com/services) like in-depth performance reports and benchmarks across multiple clouds. If you're interested in something like that, I'm sure they'd let you pay for their services, and presumably provide services worth paying for.

**Comment by imjasonh** [comment]
FYI Cloud Run is available in all regions, and now so is gcping!
