### ISSUE TITLE
US-East4 [Northern Virginia] Not Showing On GCPing.com

### ISSUE THREAD

**Issue by IanDLacy** [ImJasonH/gcping#33]
It was showing the other day, but now it's not.
I know nothing else.
I thought you might want to know in case you haven't noticed it yet.

**Comment by imjasonh** [comment]
Weird! Not only that, but trying to view gcping.com from the northeast US resulted in a 404! 💥 

It should be fixed now. I think it might have been caused by https://github.com/ImJasonH/gcping/commit/f424d0bf68c0f5587b3192f0e6994c99ce772de6

**Comment by IanDLacy** [comment]
Looks good now!
Your site is an extremely convenient little tool.
It's much appreciated!

**Comment by imjasonh** [comment]
Thanks! That's always nice to hear. 🥰
