### ISSUE TITLE
Three regions in US-West are missing  

### ISSUE THREAD

**Issue by technokrak** [ImJasonH/gcping#34]
The following GCP regions are missing in the gcpping list

us-west2-a/b/c <--> Los Angeles, California, North America
us-west3-a/b/c <--> Salt Lake City, Utah, North America
us-west4-a/b/c <--> Las Vegas, Nevada, North America

Could you please include them ?

**Comment by imjasonh** [comment]
Cloud Run doesn't support these locations: https://cloud.google.com/run/docs/locations. Since GCPing runs on Cloud Run, this is working as intended.

cc @ahmetb since this seems to come up a lot (last in #32)

**Comment by imjasonh** [comment]
FYI Cloud Run is available in all regions, and now so is gcping!
