### ISSUE TITLE
New region europe-central2 (Warsaw)

### ISSUE THREAD

**Issue by zdenulo** [ImJasonH/gcping#36]
There is available new region in Warsaw (Poland) europe-central2, which is not yet included in GCP ping. I think Cloud Run is not supported there yet, though.

**Comment by imjasonh** [comment]
Thanks for the heads up!

It looks like it's not live for Cloud Run yet, but I'll keep an eye on it  👀

**Comment by Mistic92** [comment]
Hi, Cloud Run is live, I think we can add it to tool

**Comment by imjasonh** [comment]
Done! 5d69e83d6496ab8e4f6f9cf4b05144d5215b02b8

<img width="505" alt="Screen Shot 2021-04-11 at 6 32 49 AM" src="https://user-images.githubusercontent.com/210737/114300731-bdc90200-9a8f-11eb-8715-ab7e1c7cd14c.png">
