### ISSUE TITLE
New region Delhi (asia-south2)

### ISSUE THREAD

**Issue by ansarizeeshan** [ImJasonH/gcping#38]
There is a new region in Delhi (India - asia-south2), which is not yet included in GCP ping. Also, Cloud Run is supported in this region.
![image](https://user-images.githubusercontent.com/7957173/125737157-d03c720c-b6b8-4806-92e9-12330b93db55.png)

**Comment by imjasonh** [comment]
Added australia-southeast2 (Melbourne) and asia-south2 (Delhi) in https://github.com/imjasonh/gcping/commit/eaaedd16707ee7d5adb5a84717492a54d6738a37

Thanks for bringing this to my attention! 👍
