### ISSUE TITLE
Consistency with Region name on web UI

### ISSUE THREAD

**Issue by ansarizeeshan** [ImJasonH/gcping#39]
It will be highly appreciatable if we have the region name along with the country name.

![image](https://user-images.githubusercontent.com/7957173/126057417-babd9920-f459-41cb-9dc5-15758580f973.png)

**Comment by imjasonh** [comment]
I agree!

gcping is actually in the process of being moved to the GCP GitHub org and real Google ownership.

If you want to propose this change you can do so by changing https://github.com/GoogleCloudPlatform/gcping/blob/main/internal/config/endpoints.go over there.
